apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-external
  name: events-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-external
  strategy: {}
  template:
    metadata:
      labels:
        app: events-external
    spec:
      containers:
      - image: gcr.io/mar-roidtc310/external-image:v1.0.0
        name: events-external
        imagePullPolicy: "IfNotPresent"
        env:
        - name: SERVER
          value: "http://events-internal"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
        # readinessProbe:
        #   httpGet:
        #     #path: /health
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     port: 80
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        
status: {}
